/**
 * Mock Generate Initial Data Handler
 *
 * Drop-in replacement for generateInitialDataHandler that creates
 * deterministic synthetic records directly in IndexedDB, skipping
 * the LLM call entirely. Used during E2E testing when data content
 * doesn't matter — only the record structure and count.
 *
 * Activation:
 *   localStorage.setItem('vllora_mock_data_generation', 'true')
 *
 * Produces the same record shape, metadata, progress events, and
 * return type as the real handler so downstream code (eval, training,
 * skill packaging) works identically.
 */

import { datasetService, recordService } from '@/services/service-registry';
import type { ToolHandler } from '@/lib/distri-finetune-tools/types';
import type { TopicHierarchyNode } from '@/types/dataset-types';
import { emitter } from '@/utils/eventEmitter';

// =============================================================================
// Mock-aware dispatch (single source of truth for the localStorage check)
// =============================================================================

/** Returns true when mock data generation is enabled via localStorage. */
export function isMockDataGenerationEnabled(): boolean {
  try {
    return localStorage.getItem('vllora_mock_data_generation') === 'true';
  } catch {
    return false;
  }
}

/**
 * Wraps a real handler with the mock check.
 * Call sites just do: `await maybeUseMockHandler(realHandler, params)`
 */
export async function maybeUseMockHandler(
  realHandler: ToolHandler,
  params: Record<string, unknown>,
): Promise<unknown> {
  if (isMockDataGenerationEnabled()) {
    return mockGenerateInitialDataHandler(params);
  }
  return realHandler(params);
}

// =============================================================================
// Types (mirrors generate-initial-data.ts)
// =============================================================================

interface GenerateInitialDataParams {
  workflow_id: string;
  count?: number;
  user_guidance?: string;
  distribute_by_topic?: boolean;
  target_topics?: string[];
  per_topic_count?: number;
}

interface GenerateInitialDataResult {
  success: boolean;
  error?: string;
  dataset_name?: string;
  records_created?: number;
  training_objective?: string;
  knowledge_sources_used?: number;
}

interface LeafTopic {
  readonly name: string;
  readonly path: readonly string[];
}

// =============================================================================
// Helpers
// =============================================================================

const MOCK_BATCH_SIZE = 25;
const MOCK_BATCH_DELAY_MS = 100;

function getLeafTopics(
  hierarchy: readonly TopicHierarchyNode[],
  parentPath: readonly string[] = [],
): LeafTopic[] {
  const leaves: LeafTopic[] = [];
  for (const node of hierarchy) {
    const currentPath = [...parentPath, node.name];
    if (!node.children || node.children.length === 0) {
      leaves.push({ name: node.name, path: currentPath });
    } else {
      leaves.push(...getLeafTopics(node.children, currentPath));
    }
  }
  return leaves;
}

function distributeCount(total: number, buckets: number): number[] {
  if (buckets <= 0) return [];
  const base = Math.floor(total / buckets);
  const remainder = total % buckets;
  return Array.from({ length: buckets }, (_, i) => base + (i < remainder ? 1 : 0));
}

/** Deterministic pseudo-random score between 0.50 and 0.95 */
function mockScore(index: number): number {
  const raw = ((index * 7 + 13) % 46) / 100 + 0.50;
  return Math.round(raw * 100) / 100;
}

/** Build a record for topic-based distribution (has topic + topic_path). */
function buildTopicRecord(
  topicName: string,
  topicPath: string,
  systemPrompt: string,
  index: number,
) {
  return {
    data: {
      input: {
        messages: [
          { role: 'system' as const, content: systemPrompt },
          {
            role: 'user' as const,
            content: `[Mock E2E] Explain "${topicName}" concept #${index + 1} for a beginner.`,
          },
        ],
        tools: [],
      },
      output: {
        messages: undefined,
        finish_reason: undefined,
      },
    },
    is_generated: true,
    topic: topicName,
    metadata: {
      generation_source: 'initial_data',
      generated_at_ms: Date.now(),
      topic_path: topicPath,
      skillResponse: `[Mock E2E] Here is a clear explanation of "${topicName}" concept #${index + 1}. This response was generated by the mock data handler for E2E testing.`,
      baseScore: mockScore(index),
      sourceChunkRefs: [],
    },
  };
}

/** Build a record for flat distribution (no topic fields — matches real handler). */
function buildFlatRecord(
  systemPrompt: string,
  index: number,
) {
  return {
    data: {
      input: {
        messages: [
          { role: 'system' as const, content: systemPrompt },
          {
            role: 'user' as const,
            content: `[Mock E2E] Question #${index + 1} for training.`,
          },
        ],
        tools: [],
      },
      output: {
        messages: undefined,
        finish_reason: undefined,
      },
    },
    is_generated: true,
    metadata: {
      generation_source: 'initial_data',
      generated_at_ms: Date.now(),
      skillResponse: `[Mock E2E] Answer #${index + 1}. This response was generated by the mock data handler for E2E testing.`,
      baseScore: mockScore(index),
      sourceChunkRefs: [],
      batch_index: Math.floor(index / MOCK_BATCH_SIZE),
    },
  };
}

function delayMs(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// =============================================================================
// Mock Handler
// =============================================================================

export const mockGenerateInitialDataHandler: ToolHandler = async (
  params,
): Promise<GenerateInitialDataResult> => {
  const startTime = Date.now();
  const {
    workflow_id,
    count = 10,
    distribute_by_topic = true,
    target_topics,
    per_topic_count,
  } = params as unknown as GenerateInitialDataParams;

  if (!workflow_id) {
    return { success: false, error: 'workflow_id is required' };
  }

  // Fetch dataset (hierarchy lives on the Dataset object)
  const dataset = await datasetService.getById(workflow_id);

  if (!dataset) {
    return { success: false, error: `Dataset ${workflow_id} not found` };
  }

  const objective = dataset.datasetObjective ?? dataset.name;
  const hierarchy: TopicHierarchyNode[] = dataset.topicHierarchy?.hierarchy ?? [];

  // Emit started
  emitter.emit('vllora_data_generation_progress', {
    workflowId: workflow_id,
    status: 'started',
    total: count,
    completed: 0,
  });

  // Determine record distribution
  let leafTopics = getLeafTopics(hierarchy);

  // Filter to target topics if specified
  if (target_topics && target_topics.length > 0) {
    const targetSet = new Set(target_topics);
    leafTopics = leafTopics.filter((t) => targetSet.has(t.name));
  }

  let totalGenerated = 0;
  const totalBatches = Math.ceil(count / MOCK_BATCH_SIZE);

  if (distribute_by_topic && leafTopics.length > 0) {
    // Topic-based distribution
    const effectiveCount = per_topic_count
      ? per_topic_count * leafTopics.length
      : count;
    const perTopicCounts = per_topic_count
      ? Array.from({ length: leafTopics.length }, () => per_topic_count)
      : distributeCount(effectiveCount, leafTopics.length);

    let batchIndex = 0;

    for (let t = 0; t < leafTopics.length; t++) {
      const topic = leafTopics[t];
      const topicCount = perTopicCounts[t];
      const topicPath = topic.path.join(' > ');
      const systemPrompt = `You are an expert assistant specializing in ${topicPath}. Provide clear, helpful responses.`;

      // Generate records for this topic in batches
      for (let offset = 0; offset < topicCount; offset += MOCK_BATCH_SIZE) {
        const batchSize = Math.min(MOCK_BATCH_SIZE, topicCount - offset);
        const records = Array.from({ length: batchSize }, (_, i) =>
          buildTopicRecord(topic.name, topicPath, systemPrompt, offset + i),
        );

        await recordService.add(workflow_id, records);
        totalGenerated += batchSize;
        batchIndex++;

        // Emit progress
        emitter.emit('vllora_data_generation_progress', {
          workflowId: workflow_id,
          status: 'progress',
          total: count,
          completed: totalGenerated,
          currentBatch: batchIndex,
          totalBatches,
          currentTopic: topic.name,
          topicCompleted: Math.min(offset + batchSize, topicCount),
          topicTotal: topicCount,
        });

        await delayMs(MOCK_BATCH_DELAY_MS);
      }
    }
  } else {
    // Flat distribution (no topics)
    const systemPrompt = `You are a helpful assistant focused on ${objective}.`;

    for (let offset = 0; offset < count; offset += MOCK_BATCH_SIZE) {
      const batchSize = Math.min(MOCK_BATCH_SIZE, count - offset);
      const records = Array.from({ length: batchSize }, (_, i) =>
        buildFlatRecord(systemPrompt, offset + i),
      );

      await recordService.add(workflow_id, records);
      totalGenerated += batchSize;

      emitter.emit('vllora_data_generation_progress', {
        workflowId: workflow_id,
        status: 'progress',
        total: count,
        completed: totalGenerated,
        currentBatch: Math.ceil((offset + batchSize) / MOCK_BATCH_SIZE),
        totalBatches,
      });

      await delayMs(MOCK_BATCH_DELAY_MS);
    }
  }

  // Refresh UI
  emitter.emit('vllora_dataset_refresh' as never);

  // Emit completed
  emitter.emit('vllora_data_generation_progress', {
    workflowId: workflow_id,
    status: 'completed',
    total: count,
    completed: totalGenerated,
    currentBatch: totalBatches,
    totalBatches,
  });

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`[mockGenerateInitialData] Generated ${totalGenerated} mock records in ${elapsed}s`);

  return {
    success: true,
    dataset_name: dataset.name,
    records_created: totalGenerated,
    training_objective: objective,
  };
};
